Migrate to Node.js 24

diff --git a/.github/workflows/check-dist.yaml b/.github/workflows/check-dist.yaml
--- a/.github/workflows/check-dist.yaml
+++ b/.github/workflows/check-dist.yaml
@@ -1,10 +1,15 @@
-name: Check bundled JavaScript
+name: Check Transpiled JavaScript
 
 on:
   pull_request:
-    branches: [main]
+    branches:
+      - main
   push:
-    branches: [main]
+    branches:
+      - main
+
+permissions:
+  contents: read
 
 jobs:
   check-dist:
@@ -13,26 +18,50 @@ jobs:
 
     steps:
       - name: Checkout
+        id: checkout
         uses: actions/checkout@v6
 
       - name: Setup Node.js
+        id: setup-node
         uses: actions/setup-node@v6
         with:
           node-version-file: .node-version
           cache: npm
 
+      - name: Remove dist/ Directory
+        id: remove-dist
+        run: npx rimraf ./dist
+
       - name: Install Dependencies
+        id: install
         run: npm ci
 
       - name: Build dist/ Directory
+        id: build
         run: npm run bundle
 
+      # This will fail the workflow if the `dist/` directory is different than
+      # expected.
       - name: Compare Directories
         id: diff
-        run: git diff --exit-code --ignore-space-at-eol --text dist/
+        run: |
+          if [ ! -d dist/ ]; then
+            echo "Expected dist/ directory does not exist.  See status below:"
+            ls -la ./
+            exit 1
+          fi
+          git add --intent-to-add dist/
+          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
+            echo "Detected uncommitted changes after build. See status below:"
+            git diff --ignore-space-at-eol --text dist/
+            exit 1
+          fi
 
-      - name: Upload Artifact
-        if: ${{ failure() && steps.diff.outcome == 'failure' }}
+      # If `dist/` was different than expected, upload the expected version as a
+      # workflow artifact.
+      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
+        name: Upload Artifact
+        id: upload
         uses: actions/upload-artifact@v7
         with:
           name: dist
